### ISSUE TITLE
ça marche pas

### ISSUE THREAD

**Issue by ezawadzki** [rumpl/epaper#1]
ça marche pas

**Comment by rumpl** [comment]
Si

<img width="1546" alt="Screenshot 2021-11-05 at 16 01 41" src="https://user-images.githubusercontent.com/99933/140531840-1b979110-2e1b-46e1-af30-5f71880f36cf.png">

**Comment by ezawadzki** [comment]
c'était pour t'embêter

**Comment by rumpl** [comment]
![image](https://user-images.githubusercontent.com/99933/140532663-c4b61d7a-4881-4b82-a10d-9840abdbbd2a.png)
